name: Run tests

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build
        run: mvn -B clean compile

      - name: Run tests
        run: mvn -B test
